### ISSUE TITLE
Does not work on Slim3

### ISSUE THREAD

**Issue by Spomky** [willrowe/php-recaptcha#1]
As this library does not work on Slim 3, you should add a constraint `"slim/slim": "^2.0"` to the slim dependency (at the moment it is set in the dev-deps which makes no sense).

**Comment by willrowe** [comment]
Thanks for the feedback.

Since this package supports both Twig and Slim and they can be used separately or not at all, I did not want to require either of them when installing. They are basically optional adapters, so the programmer chooses what to install in addition.

I have added a version compatibility section to the readme file to make it more clear what versions are supported.
